[package]
name = "arbor"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
tokio = { version = "1.40.0", features = ["full"] }
dirs = { version = "4.0" }
clap = { version = "4.5.20", features = ["derive"] }
